### ISSUE TITLE
Review pyhdf5io

### ISSUE THREAD

**Issue by mskoenz** [FrescolinoGroup/pyhdf5io#1]

**Comment by mskoenz** [comment]
Very nice and clean code, here my small remarks/questions?

 * _base_classes.py 
ok
 * _version.py
ok
 * _save_load.py
Is a hdf5-error desired if I deserialize a non HDF5Enables object? (You wont find TYPE_TAG_KEY), or should pyhdf5io raise a more specific error? (maybe used wrong file, wrong handle...), also maybe a nicer error instead of keyerror if loaded in a file that did not include the class?

* _special_types.py
I'm in favor of define _value_serializer before usage, e.g. on line 89.
Did I get it right (line 86), that dict with more complex immutable keys (e.g. myHDF5EnabledClass) are an issue? Can keys only be strings for now?

 * _subscribe.py
Is it legal to have a from_hdf5 but not to_hdf5 (line 35) in a custom class? I dont see the need for this asymmetry yet...
Did you checked what error you get if you dont have a from_hdf5? I assume ABC triggers first and produces a nice error.
Is there a nice error if I forget to derive from HDF5Enabled?

**Comment by mskoenz** [comment]
ready for dev-feedback/changes

**Comment by greschd** [comment]
### _save_load

Added two ``try / except`` blocks to create nicer error messages. At some point I probably want to include a plugin system that will auto-import the class defining a given ``type_tag`` when to avoid the problem of having to import everything before loading works. But that can easily be added later.

### _special_types

My convention is to define the functions _after_ they are used -- it makes for a better "flow of reading" IMHO. First you see the high-level picture, and then you see more and more details in the low-level implementation functions.

For the dict, I now changed it to serialize the ``.items()`` directly. This means that any serializable (and hashable) type can be used.

### _subscribe

The reason for this asymmetry are the special types: They have a helper class which is subscribed for de-serialization, but obviously serialization needs to happen directly in the ``to_hdf5`` free function, since I cannot give members to the built-in classes.

I don't want to make a distinction between custom and other classes in ``subscribe_serialize``, but only ``HDF5Enabled`` is exposed to the public (``Serializable`` and ``Deserializable`` are not).

In principle I could check if it's an subclass of ``Deserializable`` when subscribing, but I don't think that's necessary. If a user just wants to go by duck-typing (e.g. so that they can use another metaclass) that should be allowed. 

~~To make that work nicely, I changed the ``to_hdf5`` function so that it just tries to call ``obj.to_hdf5`` in the base implementation, instead of only doing that for ``HDF5Enabled`` subclasses.~~
When a user wants to use duck-typing instead of using ``HDF5Enabled``, they'll have to register the class with ``to_hdf5``. Duck-typing in ``to_hdf5`` instead is a bad idea because it can be shadowed by other specializations of ``to_hdf5``. For example, if the user then decides later to add an ``__iter__`` method to the class, it will be serialized by the ``Iterable`` specialization instead of going through the proper mechanism.

Another option would be to have ``to_hdf5`` explicitly check if the object has a ``to_hdf5`` attribute, and only when that fails delegate to a single-dispatched implementation function. That function should probably also be public, since we want to enable registering new types. What's your opinion on this?

**Comment by greschd** [comment]
The error when you don't define ``from_hdf5`` will just be the regular Python ``AttributeError``, which I think is clear enough.

**Comment by greschd** [comment]
@mskoenz Ready for further review / comments.

**Comment by greschd** [comment]
**Update:** I implemented the option where the singledispatch in ``to_hdf5`` is moved to a separate function here: https://github.com/FrescolinoGroup/pyhdf5io/tree/option_separate_singledipatch_function

**Comment by mskoenz** [comment]
* _save_load.py
ok

* _special_types.py
~~I'm in favor of define _value_serializer before usage~~
ok

 * _subscribe.py
ok

Currently, for a duck-typed class that is also e.g. ``__iter__``, I cannot control the ``to_hdf5``, since ``__iter__`` triggers first. For ``HDF5Enabled`` Classes this should not be a problems, since this is single-dispatched.
~~But if you support duck-typed classes just as well as ``HDF5Enabled`` classes, why would I ever derive...~~ for ``to_hdf5_file`` & ABC check

1) Leave as is if duck-typed + special type inherit/subclass is an edge-case
2) change, ~~but then also drop the ``HDF5Enabled`` inheritance~~?

**Comment by mskoenz** [comment]
in favor of changing to ``option_separate_singledipatch_function``
@greschd: ready for final changes
